### ISSUE TITLE
grc file for vhf_transceiver.py

### ISSUE THREAD

**Issue by arun121cs** [argilo/contest-sdr#1]
I am having issues running vhf_transceiver.py. Can i have the grc file for this module?

**Comment by argilo** [comment]
There is no GRC file for vhf_transceiver.py. I wrote that script by hand.

**Comment by arun121cs** [comment]
I am not able to run as pyqt4 is giving constant errors. Can you help me?

**Comment by argilo** [comment]
You'll have to provide a lot more information before I can diagnose the problem. Which operating system are you using? Which version? How did you install GNU Radio and which version do you have? What exactly are the errors you're seeing?

**Comment by arun121cs** [comment]
I am basically trying to transmit a signal and receive it back. I tried to combine the transmitter and receiver using a selector and my idea is to switch the tx and rx with a speed such that i can receive the signal i am sending. I am having half duplex hackrf one device thats why i am trying to do so, but so far i havent found any success thats why i am trying random files which work for both tx and rx.  This is my basic problem. 
Now my questions are:
1. Is it practically possible to do this?
2. If so, what should i try?
I am working on ubuntu and i have built gnuradio from source.

I know previous question does not relate here, that came up when i tried to run vhf_transceiver.py so i can get anything out of it. I installed pyqt4 and gnuradio and still it is giving me errors like "no module like QWidget " and many. 

So my main question is that is it possible what i am trying, and if you have ever done anything like this which involves rapid switching between tx and rx. 
Thanks in advance.

**Comment by argilo** [comment]
Unfortunately T/R switching does not work well with the HackRF. And I doubt it's capable of doing what you want.

First off, gr-osmosdr does not support T/R switching without modification, so you need to compile a custom version of it. Second, switching between tx and rx is very slow, on the order of hundreds of milliseconds.

I expect you'd be better off working with a full-duplex SDR like a USRP.
